import { vi } from "vitest";

Object.assign(globalThis, {
  Game: {
    time: 12345,
    getObjectById: () => undefined,
    creeps: {},
  },
  Memory: {
    creeps: {},
    tasks: {},
    rooms: {},
  },
  RESOURCE_ENERGY: "energy",
  WORK: "work",
  CARRY: "carry",
  MOVE: "move",
  STRUCTURE_SPAWN: "spawn",
  STRUCTURE_EXTENSION: "extension",
  STRUCTURE_CONTAINER: "container",
  STRUCTURE_STORAGE: "storage",
  STRUCTURE_TERMINAL: "terminal",
  STRUCTURE_ROAD: "road",
  STRUCTURE_WALL: "wall",
  STRUCTURE_RAMPART: "rampart",
  FIND_SOURCES: 10,
  FIND_DROPPED_RESOURCES: 11,
  FIND_STRUCTURES: 12,
  FIND_MY_STRUCTURES: 13,
  FIND_MY_CONSTRUCTION_SITES: 14,
  FIND_MY_SPAWNS: 15,
  OK: 0,
  ERR_NOT_IN_RANGE: -9,
  ERR_NOT_ENOUGH_RESOURCES: -6,
  ERR_BUSY: -4,
  ERR_INVALID_TARGET: -7,
  ERR_NOT_OWNER: -1,
  ERR_NO_BODYPART: -12,
  STRUCTURE_TOWER: "tower",
  STRUCTURE_LINK: "link",
  STRUCTURE_LAB: "lab",
  STRUCTURE_FACTORY: "factory",
  STRUCTURE_POWER_SPAWN: "powerSpawn",
  STRUCTURE_EXTRACTOR: "extractor",
  STRUCTURE_NUKER: "nuker",
  STRUCTURE_OBSERVER: "observer",
  TERRAIN_MASK_WALL: 1,
  TERRAIN_MASK_SWAMP: 2,
  CONTROLLER_STRUCTURES: {
    spawn: [0, 1, 1, 1, 1, 1, 1, 1, 1],
    extension: [0, 0, 5, 10, 20, 30, 40, 50, 60],
    tower: [0, 0, 0, 1, 1, 2, 2, 3, 4],
    link: [0, 0, 0, 0, 0, 0, 2, 3, 4],
    storage: [0, 0, 0, 0, 1, 1, 1, 1, 1],
    extractor: [0, 0, 0, 0, 0, 0, 1, 1, 1],
    lab: [0, 0, 0, 0, 0, 0, 3, 6, 10],
    factory: [0, 0, 0, 0, 0, 0, 0, 1, 1],
    powerSpawn: [0, 0, 0, 0, 0, 0, 0, 0, 1],
    nuker: [0, 0, 0, 0, 0, 0, 0, 0, 1],
    observer: [0, 0, 0, 0, 0, 0, 0, 0, 1],
    container: [0, 0, 0, 0, 0, 0, 0, 0, 0],
  },
});
